---
# role: ansible-role-common
# file: tasks/main.yml

- name: "Tasks for ansible-role-common"
  block:
    - name: "Set os_family dependent variables"
      include_vars: '{{ ansible_os_family }}.yml'

    - name: "Set distribution dependent variables"
      include_vars: "{{ item }}"
      vars:
        params:
          files:
            - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
            - '{{ ansible_distribution }}.yml'
            - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
            - '{{ ansible_os_family }}.yml'
          paths:
            - 'vars'
      loop: "{{ query('first_found', params) }}"

    # Include parses files on runtime.
    # Import does not work, because ansible_pkg_mgr is unknown before gather_facts.
    - name: "Import package manager specific tasks"
      include_tasks: "{{ ansible_pkg_mgr }}.yml"

    - name: "Install specified packages"
      package:
        name: "{{ common_install }}"
        state: present
  when: common_role_enabled | bool
