---
# role: ansible-role-common
# file: tasks/network.yml

- name: "{{ common_ipv6_enabled | ternary('Enable', 'Disable') }} IPv6"
  sysctl:
    name: "{{ item }}"
    value: "{{ common_ipv6_enabled | ternary(0, 1) }}"
    sysctl_set: yes
    state: present
    reload: yes
    sysctl_file: "/etc/sysctl.d/40-ipv6.conf"
  loop:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6
