---
# role: ansible-role-common
# file: tasks/tasks.yml

- name: Set os_family dependent variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: Set distribution dependent variables
  include_vars: '{{ vars_file }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
      skip: true
  loop_control:
    loop_var: vars_file

- name: Install packages for ansible-role-common
  package:
    name: "{{ common_package }}"
    state: present
  loop: "{{ common_packages }}"
  loop_control:
    loop_var: common_package

- name: Include tasks for setting hostname
  include_tasks: hostname.yml

- name: Include tasks for network configuration
  include_tasks: network.yml
