---
# role: ansible-role-common
# file: tasks/tasks.yml

- name: "Set os_family dependent variables"
  include_vars: '{{ ansible_os_family }}.yml'

- name: "Set distribution dependent variables"
  include_vars: '{{ vars_file }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
      skip: true
  loop_control:
    loop_var: vars_file

# This installs e.g. apt-transport-https, to enable https repo urls.
- name: "Install packages for ansible-role-common"
  package:
    name: "{{ common_packages }}"
    state: present

# Configure specified repositories, with https by default, of course.
- name: "Import tasks for repository installation"
  import_tasks: repos.yml

# Install custom packages of your choice after repo setup.
- name: "Import tasks for package installation"
  import_tasks: packages.yml
