---
# role: ansible-role-common
# file: molecule/vbox/molecule.yml

dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
    type: virtualbox
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: common-alpine312
    box: "generic/alpine312"
    cpus: 2
    memory: 1024
  - name: common-amazonlinux2
    box: "bento/amazonlinux-2"
    cpus: 2
    memory: 1024
  - name: common-arch
    box: "archlinux/archlinux"
    cpus: 2
    memory: 1024
  - name: common-centos7
    box: "centos/7"
    cpus: 2
    memory: 1024
  - name: common-centos8
    box: "centos/8"
    cpus: 2
    memory: 1024
  - name: common-debian9
    box: "debian/stretch64"
    cpus: 2
    memory: 1024
  - name: common-debian10
    box: "debian/buster64"
    cpus: 2
    memory: 1024
  - name: common-fedora32
    box: "fedora/32-cloud-base"
    cpus: 2
    memory: 4096
  - name: common-manjaro
    box: "jam82/manjaro-20.1-xfce-minimal"
    cpus: 2
    memory: 4096
  - name: common-suse-leap-15
    box: "bento/opensuse-leap-15"
    cpus: 2
    memory: 1024
  - name: common-oracle7
    box: "generic/oracle7"
    cpus: 2
    memory: 1024
  - name: common-oracle8
    box: "generic/oracle8"
    cpus: 2
    memory: 1024
  - name: common-ubuntu1804
    box: "ubuntu/bionic64"
    cpus: 2
    memory: 1024
  - name: common-ubuntu2004
    box: "ubuntu/focal64"
    cpus: 2
    memory: 1024
provisioner:
  name: ansible
  log: true
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
  inventory:
    group_vars:
      all:
        common_role_enabled: true
verifier:
  name: ansible
