---
# role: ansible-role-common
# file: molecule/vbox/molecule.yml

dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
    type: virtualbox
    options:
      gui: True
      memory: 2048
      cpus: 2
      provision: True
lint:
  name: yamllint
  options:
    config-file: molecule/shared/yamllint.yml
platforms:
  - name: common-alpine310
    box: "generic/alpine310"
  - name: common-arch
    box: "archlinux/archlinux"
  - name: common-centos8
    box: "centos/8"
  - name: common-debian10
    box: "debian/buster64"
  - name: common-fedora31
    box: "fedora/31-cloud-base"
  - name: common-ubuntu1804
    box: "ubuntu/bionic64"
provisioner:
  name: ansible
  log: True
  lint:
    name: ansible-lint
  playbooks:
    prepare: prepare.yml
    converge: ../shared/playbook.yml
  inventory:
    group_vars:
      all:
        common_enabled: True
scenario:
  name: vbox
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore"
  directory: ../tests
  options:
    v: True
    sudo: True
  lint:
    name: flake8
