---
# role: ansible-role-common
# file: molecule/kvm/molecule.yml

dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt
    options:
      memory: 2048
      cpus: 2
lint:
  name: yamllint
  options:
    config-file: molecule/shared/yamllint.yml
platforms:
  - name: common-alpine310
    box: "generic/alpine310"
  # - name: common-arch
  #   box: "archlinux/archlinux"
  # - name: common-centos7
  #   box: "centos/7"
  # - name: common-debian9
  #   box: "debian/buster64"
  - name: common-ubuntu1804
    box: "generic/ubuntu1804"
provisioner:
  name: ansible
  log: True
  lint:
    name: ansible-lint
  playbooks:
    prepare: prepare.yml
    converge: ../shared/playbook.yml
  inventory:
    group_vars:
      all:
        common_enabled: True
scenario:
  name: kvm
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore"
  directory: ../tests
  options:
    v: True
    sudo: True
  lint:
    name: flake8
