---
# role: ansible-role-common
# file: molecule/resources/playbooks/converge.yml

- name: Converge
  hosts: all
  become: true
  gather_facts: true
  vars:
    common_role_enabled: true
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
