---
# role: ansible-role-common
# file: molecule/resources/playbooks/prepare.yml

- name: Prepare
  hosts: all
  become: true
  gather_facts: false
  roles:  # see requirements.yml in root directory of this role
    - baseline
